spring:
  cloud:
    gateway:
      routes:
        - id: test_route_baidu
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: test_route_qq
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
    nacos:
      discovery:
        server-addr: 192.168.77.100:8848